# Generated by Django 5.0.6 on 2024-07-05 09:57

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('_password', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.creator')),
            ],
        ),
        migrations.CreateModel(
            name='News_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_p', models.ImageField(upload_to='posts/img')),
                ('videos_p', models.FileField(upload_to='posts/videos')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.creator')),
            ],
        ),
    ]
