# Generated by Django 5.0.6 on 2024-07-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_posts_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name_plural': 'Creators'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Creators'},
        ),
        migrations.AlterModelOptions(
            name='news_posts',
            options={'verbose_name_plural': 'News_posts'},
        ),
        migrations.AlterModelOptions(
            name='post_comments',
            options={'verbose_name_plural': 'Post_comments'},
        ),
    ]
