# Generated by Django 5.0.6 on 2024-07-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_creator_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
